import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "../style/globals.css";
import SiteLayout from "./layouts/SiteLayout";
import BreadcrumbAuto from "@/components/ui/BreadcrumbAuto";
import {CartProvider} from "@/context/CartProvider";

const poppinsFonts = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nextjs Fakestore e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsFonts.className} antialiased`}>
        <CartProvider>
          <SiteLayout>
            <BreadcrumbAuto />
            {children}
          </SiteLayout>
        </CartProvider>
      </body>
    </html>
  );
}
